const data = [
    {
        name:"Nikhil",
        className:"BSC",
        roll_no:"",
        profession:""
    },
    {
        name:"",
        className:"",
        roll_no:"",
        profession:""
    },
    {
        name:"",
        className:"",
        roll_no:"",
        profession:""
    },
    {
        name:"",
        className:"",
        roll_no:"",
        profession:""
    }
]